#
# Authproxy
#
[Authproxy.HttpServer]
AllowedHosts = ["127.0.0.1:8000"]
AccessControlAllowOrigin = "http://127.0.0.1:3000"


#
# Monitor
#
[Monitor.ApiApp]
Name = "api"
ClientTimeout = 5
ShutdownTimeout = 10
LoopInterval = 10
CertFile = "server.pem"
KeyFile = "server.key"
CaFile = "ca.pem"
ServerHostOverride = "x.test.youtube.com"
Listen = "127.0.0.1:13200"
Targets = ["127.0.0.1:13200"]

[Monitor.Database]
Connection = "goapp:goapppass@tcp(127.0.0.1:3306)/goapp_monitor?charset=utf8&parseTime=true"

[[Monitor.Indexers]]
Driver = "influxdb"
Indexes = ["tokyo1"]
AlertDatabases = ["goapp:goapppass@http://127.0.0.1:8086@goapp_monitor_alerts"]
LogDatabases = ["goapp:goapppass@http://127.0.0.1:8086@goapp_monitor_logs"]
MetricDatabases = ["goapp:goapppass@http://127.0.0.1:8086@goapp_monitor_metrics"]
PercistentDatabases = ["goapp:goapppass@http://127.0.0.1:8086@goapp_monitor_percistent"]

[Monitor.AlertManagerApp]
Name = "alert-manager"
ClientTimeout = 5
ShutdownTimeout = 10
LoopInterval = 10
CertFile = "server.pem"
KeyFile = "server.key"
CaFile = "ca.pem"
ServerHostOverride = "x.test.youtube.com"
Listen = "127.0.0.1:13201"
Targets = ["127.0.0.1:13201"]

[Monitor.AgentApp]
Name = "agent"
ClientTimeout = 5
ShutdownTimeout = 10
LoopInterval = 10
CertFile = "server.pem"
KeyFile = "server.key"
CaFile = "ca.pem"
ServerHostOverride = "x.test.youtube.com"
Listen = "127.0.0.1:13202"
Targets = ["127.0.0.1:13202"]
LogReaderRefreshSpan = 3
ReportIndex = "cluster1"
ReportProject = "admin"
ReportSpan = 3

[Monitor.AgentApp.LogMap."monitor-api"]
Path = "goapp-authproxy.log"
MaxInitialReadSize = 10000

[Monitor.AgentApp.LogMap."monitor-api".AlertMap."FoundError"]
Key = "Level"
Pattern = "E"
Level = "E"
Handler = "Mail"

[Monitor.AgentApp.Metrics.System]
Enable = true
EnableLogin = true
EnableCpu = true
EnableMemory = true
CacheLength = 10


#
# Resource
#
[Resource]
AppDownTime = 120

[Resource.ApiApp]
Name = "api"
ClientTimeout = 5
ShutdownTimeout = 10
LoopInterval = 10
CertFile = "server.pem"
KeyFile = "server.key"
CaFile = "ca.pem"
ServerHostOverride = "x.test.youtube.com"
Listen = "127.0.0.1:13300"
Targets = ["127.0.0.1:13300"]

[Resource.ControllerApp]
Name = "api"
ClientTimeout = 5
ShutdownTimeout = 10
LoopInterval = 10
SyncResourceTimeout = 30
CertFile = "server.pem"
KeyFile = "server.key"
CaFile = "ca.pem"
ServerHostOverride = "x.test.youtube.com"
Listen = "127.0.0.1:13301"
Targets = ["127.0.0.1:13301"]

[Resource.Database]
Connection = "goapp:goapppass@tcp(127.0.0.1:3306)/goapp_resource?charset=utf8&parseTime=true"

[Resource.ClusterMap."tokyo1".Database]
Connection = "goapp:goapppass@tcp(127.0.0.1:3306)/goapp_resource_tokyo1?charset=utf8&parseTime=true"

[Resource.ClusterMap."tokyo1".ApiApp]
Name = "api"
ClientTimeout = 5
ShutdownTimeout = 10
LoopInterval = 10
CertFile = "server.pem"
KeyFile = "server.key"
CaFile = "ca.pem"
ServerHostOverride = "x.test.youtube.com"
Listen = "127.0.0.1:13310"
Targets = ["127.0.0.1:13310"]

[Resource.ClusterMap."tokyo1".ControllerApp]
Name = "api"
ClientTimeout = 5
ShutdownTimeout = 10
LoopInterval = 10
CertFile = "server.pem"
KeyFile = "server.key"
CaFile = "ca.pem"
ServerHostOverride = "x.test.youtube.com"
Listen = "127.0.0.1:13311"
Targets = ["127.0.0.1:13311"]

[Resource.ClusterMap."tokyo1".AgentApp]
Name = "api"
ClientTimeout = 5
ShutdownTimeout = 10
LoopInterval = 10
CertFile = "server.pem"
KeyFile = "server.key"
CaFile = "ca.pem"
ServerHostOverride = "x.test.youtube.com"
Listen = "127.0.0.1:13312"
Targets = ["127.0.0.1:13312"]
Labels = ["NwAz=nw1", "NodeAz=node1", "PowerAz=power1"]

[Resource.Node]
ClusterName = "tokyo1"

[Resource.Node.Compute]
Enable = true
Driver = "libvirt"
ConfirmRetryCount = 2
ConfirmRetryInterval = 3

[Resource.Node.Compute.Libvirt]
AvailableCpus = "1-11"
CpuMode = "host-model"
CpuType = "kvm"
MemoryType = "hugepage"
DiskType = "local"
NetworkType = "local-linuxbridge"
NetworkVhostQueues = 1

[Resource.Node.Metrics.System]
Enable = true
EnableLogin = true
EnableCpu = true
EnableMemory = true
CacheLength = 10
