authproxy:
  app:
    listen: '0.0.0.0:8000'
    allowedHosts: ['127.0.0.1:8000']
    accessControlAllowOrigin: '127.0.0.1:3000'
    certFile: 'tls-assets/server.pem'
    keyFile: 'tls-assets/server.key'
    gracefulTimeout: 10
    database:
      connection: 'goapp:goapppass@tcp(127.0.0.1:3306)/goapp_monitor?charset=utf8&parseTime=true'
    auth:
      secrets: ['changeme1', 'changeme2']
      defaultUsers:
        - {name: 'admin', password: 'admin', roles: ['admin']}
        - {name: 'service', password: 'service', roles: ['service']}
        - {name: 'guest', password: 'guest', roles: ['guestpj-member']}
      defaultRoles:
        - {name: 'admin', project: 'admin'}
        - {name: 'service', project: 'service'}
        - {name: 'guestpj-member', project: 'guestpj'}
      defaultProjects:
        - {name: 'admin', projectRole: 'admin'}
        - {name: 'service', projectRole: 'service'}
        - {name: 'guestpj', projectRole: 'tenant'}
      defaultProjectRoles:
        - {name: 'admin', services: ['Auth', 'Service', 'Home', 'Home.Project']}
        - {name: 'service', services: ['Auth', 'Service']}
        - {name: 'tenant', services: ['Auth', 'Home', 'Home.Project']}
