[Resource]
AppDownTime = 120

[Resource.ApiApp]
Name = "api"
ClientTimeout = 5
ShutdownTimeout = 10
LoopInterval = 10
CertFile = "server.pem"
KeyFile = "server.key"
CaFile = "ca.pem"
ServerHostOverride = "x.test.youtube.com"
Listen = "localhost:13300"
Targets = ["localhost:13300"]

[Resource.ControllerApp]
Name = "api"
ClientTimeout = 5
ShutdownTimeout = 10
LoopInterval = 10
CertFile = "server.pem"
KeyFile = "server.key"
CaFile = "ca.pem"
ServerHostOverride = "x.test.youtube.com"
Listen = "localhost:13301"
Targets = ["localhost:13301"]

[Resource.Database]
Connection = "admin:adminpass@tcp(localhost:3306)/goapp_resource?charset=utf8&parseTime=true"

[Resource.Cluster]
Name = "cluster1"

[Resource.ClusterMap."cluster1".ApiApp]
Name = "api"
ClientTimeout = 5
ShutdownTimeout = 10
LoopInterval = 10
CertFile = "server.pem"
KeyFile = "server.key"
CaFile = "ca.pem"
ServerHostOverride = "x.test.youtube.com"
Listen = "localhost:13310"
Targets = ["localhost:13310"]

[Resource.ClusterMap."cluster1".ControllerApp]
Name = "api"
ClientTimeout = 5
ShutdownTimeout = 10
LoopInterval = 10
CertFile = "server.pem"
KeyFile = "server.key"
CaFile = "ca.pem"
ServerHostOverride = "x.test.youtube.com"
Listen = "localhost:13311"
Targets = ["localhost:13311"]

[Resource.ClusterMap."cluster1".Database]
Connection = "admin:adminpass@tcp(localhost:3306)/goapp_resource_cluster1?charset=utf8&parseTime=true"
