[Default]
Name = "host2"

[Resource]
AppDownTime = 120

[Resource.ApiApp]
Name = "api"
ClientTimeout = 5
ShutdownTimeout = 10
LoopInterval = 10
CertFile = "server.pem"
KeyFile = "server.key"
CaFile = "ca.pem"
ServerHostOverride = "x.test.youtube.com"
Listen = "localhost:14300"
Targets = ["localhost:13300", "localhost:14300"]

[Resource.ControllerApp]
Name = "api"
Monitors = 2
ClientTimeout = 5
ShutdownTimeout = 10
LoopInterval = 10
CertFile = "server.pem"
KeyFile = "server.key"
CaFile = "ca.pem"
ServerHostOverride = "x.test.youtube.com"
Listen = "localhost:14301"
Targets = ["localhost:14301"]

[Resource.Database]
Connection = "admin:adminpass@tcp(localhost:3306)/goapp_resource?charset=utf8&parseTime=true"

[Resource.Cluster]
Name = "cluster2"

[Resource.ClusterMap."cluster2".ApiApp]
Name = "api"
ClientTimeout = 5
ShutdownTimeout = 10
LoopInterval = 10
CertFile = "server.pem"
KeyFile = "server.key"
CaFile = "ca.pem"
ServerHostOverride = "x.test.youtube.com"
Listen = "localhost:14310"
Targets = ["localhost:14310"]

[Resource.ClusterMap."cluster2".ControllerApp]
Name = "api"
ClientTimeout = 5
ShutdownTimeout = 10
LoopInterval = 10
CertFile = "server.pem"
KeyFile = "server.key"
CaFile = "ca.pem"
ServerHostOverride = "x.test.youtube.com"
Listen = "localhost:14311"
Targets = ["localhost:14311"]

[Resource.ClusterMap."cluster2".Database]
Connection = "admin:adminpass@tcp(localhost:3306)/goapp_resource_cluster2?charset=utf8&parseTime=true"
