#
# Monitor
#
[Monitor.ApiApp]
Name = "api"
ClientTimeout = 5
ShutdownTimeout = 10
LoopInterval = 10
CertFile = "server.pem"
KeyFile = "server.key"
CaFile = "ca.pem"
ServerHostOverride = "x.test.youtube.com"
Listen = "localhost:13200"
Targets = ["localhost:13200"]

[Monitor.Database]
Connection = "admin:adminpass@tcp(localhost:3306)/goapp_monitor?charset=utf8&parseTime=true"

[[Monitor.Indexers]]
Driver = "influxdb"
Indexes = ["cluster1"]
LogDatabases = ["goapp:goapppass@http://localhost:8086@goapp_monitor_logs"]
MetricDatabases = ["goapp:goapppass@http://localhost:8086@goapp_monitor_metrics"]

[Monitor.AlertManagerApp]
Name = "alert-manager"
ClientTimeout = 5
ShutdownTimeout = 10
LoopInterval = 10
CertFile = "server.pem"
KeyFile = "server.key"
CaFile = "ca.pem"
ServerHostOverride = "x.test.youtube.com"
Listen = "localhost:13201"
Targets = ["localhost:13201"]

[Monitor.AgentApp]
Name = "agent"
ClientTimeout = 5
ShutdownTimeout = 10
LoopInterval = 10
CertFile = "server.pem"
KeyFile = "server.key"
CaFile = "ca.pem"
ServerHostOverride = "x.test.youtube.com"
Listen = "localhost:13202"
Targets = ["localhost:13202"]
LogReaderRefreshSpan = 3
ReportIndex = "cluster1"
ReportProject = "admin"
ReportSpan = 3

[Monitor.AgentApp.LogMap."monitor-api"]
Path = "goapp-authproxy.log"
MaxInitialReadSize = 10000

[Monitor.AgentApp.LogMap."monitor-api".AlertMap."FoundError"]
Key = "Level"
Pattern = "E"
Handler = "Mail"

[Monitor.AgentApp.Metrics.System]
Enable = true
EnableLogin = true
EnableCpu = true
EnableMemory = true
CacheLength = 10


#
# Resource
#
[Resource]
AppDownTime = 120

[Resource.ApiApp]
Name = "api"
ClientTimeout = 5
ShutdownTimeout = 10
LoopInterval = 10
CertFile = "server.pem"
KeyFile = "server.key"
CaFile = "ca.pem"
ServerHostOverride = "x.test.youtube.com"
Listen = "localhost:13300"
Targets = ["localhost:13300"]

[Resource.ControllerApp]
Name = "api"
ClientTimeout = 5
ShutdownTimeout = 10
LoopInterval = 10
SyncResourceTimeout = 30
CertFile = "server.pem"
KeyFile = "server.key"
CaFile = "ca.pem"
ServerHostOverride = "x.test.youtube.com"
Listen = "localhost:13301"
Targets = ["localhost:13301"]

[Resource.Database]
Connection = "admin:adminpass@tcp(localhost:3306)/goapp_resource?charset=utf8&parseTime=true"

[Resource.ClusterMap."cluster1".ApiApp]
Name = "api"
ClientTimeout = 5
ShutdownTimeout = 10
LoopInterval = 10
CertFile = "server.pem"
KeyFile = "server.key"
CaFile = "ca.pem"
ServerHostOverride = "x.test.youtube.com"
Listen = "localhost:13310"
Targets = ["localhost:13310"]

[Resource.ClusterMap."cluster1".ControllerApp]
Name = "api"
ClientTimeout = 5
ShutdownTimeout = 10
LoopInterval = 10
CertFile = "server.pem"
KeyFile = "server.key"
CaFile = "ca.pem"
ServerHostOverride = "x.test.youtube.com"
Listen = "localhost:13311"
Targets = ["localhost:13311"]

[Resource.ClusterMap."cluster1".AgentApp]
Name = "api"
ClientTimeout = 5
ShutdownTimeout = 10
LoopInterval = 10
CertFile = "server.pem"
KeyFile = "server.key"
CaFile = "ca.pem"
ServerHostOverride = "x.test.youtube.com"
Listen = "localhost:13312"
Targets = ["localhost:13312"]

[Resource.ClusterMap."cluster1".Database]
Connection = "admin:adminpass@tcp(localhost:3306)/goapp_resource_cluster1?charset=utf8&parseTime=true"

[Resource.Node]
ClusterName = "cluster1"
NetworkAvailabilityZone = "nw1"
NodeAvailabilityZone = "node1"

[Resource.Node.Compute]
CpuMode = "host-model"
CpuType = "kvm"
MemoryType = "hugepage"
DiskType = "local"
NetworkType = "local-linuxbridge"
NetworkVhostQueues = 1
